### ISSUE TITLE
Duplicate contributor error message

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1082]
When trying to add the same contributor to a course twice, an error message is shown. This message differs based on whether a questionnaire was assigned or not. The error message should in both cases be the one currently shown when no questionnaire was selected.

**Current messages:**
Questionnaire selected: `Please correct the duplicate data for contributor. Please correct the duplicate values below.`
No questionnaire selected: `Duplicate contributor found. Each contributor should only be used once.`

**Comment by Pottiman** [comment]
Identified Cause:

The `Please correct the duplicate data for contributor. Please correct the duplicate values below.` message originates from Django internal unique checks.
The `Duplicate contributor found. Each contributor should only be used once.` message originates from our own checks.

Django internal unique checks only apply to all valid Forms of a FormSet. Hence, any invalid ContributionForm is not included in the unique check. A newly added contributor is invalid (set to contributes to evaluation without any questionnaires).

To resolve this, either we have to change the unique message of django internal unique checks or somehow exclude this unique check.

**Comment by janno42** [comment]
@Pottiman do you still want to work on this?

**Comment by He3lixxx** [comment]
Django code line generating the error message:
https://github.com/django/django/blob/ba42569d5c01b58b2999e393f097b530e538ec41/django/forms/models.py#L722

Django's unique validation there is kind of weird. Django does not do unique checks on the formset unless every single form is valid (I guess that's why we added our manual check?). If it does, the error message listed above in the issue is generated by two seperate parts, see my linked code part. One of these parts could be changed by overwriting a django method, the other part would have to be overwritten in a different method, so the message @janno42 listed above are actually two seperate messages.
