### ISSUE TITLE
Linting rules bikeshedding

### ISSUE THREAD

**Issue by karyon** [e-valuation/EvaP#1092]
**THIS IS OBSOLETE, check the latest comment**

right now, we only have test coverage via coveralls.

some sort of static analysis would be nice. landscape.io was nice but very unreliable.

options are:
* use https://www.codacy.com, they support prospector: https://support.codacy.com/hc/en-us/articles/213632009-Engines
* use any other service. i checked out codeclimate, but it seems they don't even support pylint. however, if we find a service that supports a set of analysis tools that seems "good enough" we can use that.
* integrate e.g. prospector/any set of tools into our tests. this would kind of require a zero-tolerance-policy since the test can only give us a failed/succeeded, and that might be annoying. maybe @janno42 can tell us how this works out in 1327.
* ???

Once we have anything like that set up, i would suggest a pass through the reports to fix the easy stuff, and maybe update our existing .pylintrc (generate a new one, transplant the changes applied to ours) and review the .landscape.yaml.

and maybe, while at it, rename .landscape.yaml to .prospector.yml.

**Comment by janno42** [comment]
in contrast to evap we wanted to enforce the linter checks in 1327, so failing tests because of linter checks (or missing migrations) are no problem there. we can discuss whether we change that for evap as well.
the repeatedly discussed downside is that new contributors have to take care of this additional thing - but in the end if we want to have nice code that might still be the way to go. i would say linter checks are common in larger projects and the additional hurdle is worth it.

but in the end i'll agree with every solution you'll propose here in this case because i don't have any strong preferences.

**Comment by He3lixxx** [comment]
I'm finde with a zero-tolerance policy for linter errors.

**Comment by janno42** [comment]
- migrations: ✔️
- protected members: ✔️
- assertions: ✔️

**Comment by janno42** [comment]
- [ ] discuss indentation
- [ ] alphabetical imports

**Comment by He3lixxx** [comment]
We ran into errors with codacy evaluating the import order because it does not set up the requirements for static code analysis, thus it can not detect third party modules - see https://github.com/fsr-de/EvaP/pull/1403#discussion_r364379207

I think this is even more a reason to run the linter on travis (where requirements are installed) and fail if anything goes wrong. We could then disable pylint on codacy and just look at the other issues they find.

I think alphabetical imports would be a good rule to have. I don't care about the indentation rules.

**Comment by He3lixxx** [comment]
Black as a code formatter was introduced in #1600
isort was introduced in #1629

This covers indentation and alphabetical imports, and I think these two were the only open points left.
