### ISSUE TITLE
Switchable staff mode

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1109]
We could add a staff and/or reviewer mode that can be activated/deactivated individually for these users.
When activated, the platform behaves as currently for staff and reviewer users. When deactivated, they use the page with their respective roles as students and/or contributors.

This improves the following:
- results pages for the current semester can optionally only show regularly published courses for these users
- default view for staff users on results pages could be "own" again, but would still be "public" when the mode is deactivated

**Comment by karyon** [comment]
More details:

* If that mode, working title: sudo mode, is enabled, the page looks and behaves *exactly* as if that user weren't a staff user/reviewer, except for some (toggle) button that enables sudo mode.

* with sudo mode enabled, the default view of result pages would be the public view. (with sudo mode disabled, there is simply no option to change views)

* the results semester view/ overview page needs a "public view" switch as well, but that's a separate issue and probably part of #571 

* sudo mode is off by default. since staff users/reviewers might just enable sudo mode and have little reason to ever disable it again, it should expire e.g. an hour after the last page load.

* implementation-wise, one possibility would be to let `is_staff` and `is_reviewer` return false if sudo mode is off. the (toggle) button would then need a new function e.g. `can_enter_sudo_mode`

* to store the activation somewhere, options would be to link that to the session (especially when we renew it on every request, see #1101), add a timestamp to the user model, or (ab)use the caching framework and put a bool in there with a timeout of one hour.

**Comment by janno42** [comment]
i don't like the name "sudo mode". superusers as defined in django have *all* permissions, so reviewers are definitely no superusers. i also wouldn't expect sudo stuff to change what are default pages for the results.

i'd say we should do the following:
- reviewers stay `reviewers`.
- current staff gets renamed to `managers`. managers also exist in the django terminology, but we aren't using them and even if we would, they would be exactly these people. we split off reviewers from the staff group, although one could argue that they are still working on the platform, so both groups are still "staff" in some way. "managers" better differentiates that.
- the extended mode can then be called `staff mode`.

i think this better represents what we're doing with it: when deactivated the users are regular students and once they activate the staff mode they are acting as staff members who are doing their work tasks on the platform.

**Comment by janno42** [comment]
We could also make the mode switch go as far as possible by letting `is_student` and `is_contributor` return false when activated. This would then remove all voting and "my courses" pages for the staff users and make clear in while role they are currently working on the platform. The mode could also be visualized with a different colored navbar or similar.
That would also enforce them to change the mode back to normal operation when using the platform in their non-staff role.

**Comment by karyon** [comment]
sounds good.

changing is_[staff|contributor|etc] might not be so easy since these are used not only for checking the current user, but also e.g. on the user list and elsewhere, we'll need to find a way around that.

**Comment by karyon** [comment]
so we talked about this once more and the distinction between reviewers and managers and both of them being staff users still makes sense.

we noticed that the staff app does not need to be renamed, since it actually is the app with the views for both managers and reviewers. similarly, the templates can keep their name, since their name is prefixed with the app name.

in the code, reviewer_required should be replaced by staff_required except where it's actually about reviewing. likewise, staff needs to be replaced by manager in some, but not all cases.

**Comment by PFischbeck** [comment]
You can find my current progress on my branch `staff-mode`, see [here](https://github.com/PFischbeck/EvaP/tree/staff-mode). It is now up to date with the master branch.
So far, I have added a staff mode attribute to the user's session. It can be actively entered/exited through a button in the navbar, and it auto-exits after one hour of no requests from the user.
Right now, it only changes which links are shown in the navbar, and also whether the buttons for different views for a results page are shown. This means that there are no server-side checks for the requests, only the views are changed.
One could change that, .e.g, by accounting for the staff mode attribute in the `..._required` decorators.

Feel free to reassign this issue and use my code as basis.

**Comment by PFischbeck** [comment]
My plan is that the navbar will display only non-staff stuff or staff stuff, depending on the staff mode. However, the navbar in staff mode now looks pretty empty. See mode off/on in comparison:
![Screenshot_2020-05-11 Results - EvaP](https://user-images.githubusercontent.com/2820802/81603889-5910ad80-93cf-11ea-952a-62f3c7658b5e.png)
vs
![Screenshot_2020-05-11 Manage - EvaP](https://user-images.githubusercontent.com/2820802/81603917-629a1580-93cf-11ea-9151-878ba616900d.png)
I think we decided on hiding the non-staff things if you're in staff mode, so that you will actively exit the mode in order to use the platform as for non-staff things.

What do you think about using this change as the opportunity to 'flatten' the `Manage` dropdown, i.e., putting every of the `Semesters`, `Publish grades` etc. stuff into the navbar itself? 
![Screenshot_2020-05-11 Manage - EvaP(1)](https://user-images.githubusercontent.com/2820802/81605063-2e275900-93d1-11ea-8601-82455e2cbc24.png)

The item list is not complete, and the full item list might be a bit much. What do you think?
I haven't thought about reviewers yet, but it might be similar there.
