### ISSUE TITLE
Group text answers for review

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1130]
This is required for issues #612, #1131 and #1132.

Text answers should be grouped per question per user by adding hashes (based on user and contribution to prevent finding all text answers over all questions that have been given by the same user) to the answers which allow to group all text answers that have been given for a question by the same user during the staff's review process. It should not be possible to (easily) find which user gave these answers.
Text answers should not be grouped anywhere else on the platform.

All grouping information should be removed when publishing the course.

**Comment by karyon** [comment]
the grouping information can be removed as soon as all comments in a particular group have been reviewed and the evaluation period has already ended.

**Comment by janno42** [comment]
I would keep the information until publishing as stated before. We can avoid struggles with reopened evaluations and it really doesn't make a big difference.

**Comment by janno42** [comment]
Fortunately this is not as big a problem as i thought. When introducing adding or editing text answers during the evaluation period we'll also change the reviewing process so that reviews will only take place after the evaluation period ended in contrast to currently working on that in parallel.
This means decisions about reopening the evaluation will then quite surely take place before the review process and we won't even have any automatic transitions into the published state that could cause any trouble for the reviews.
So all grouping information can be removed during the transition to 'reviewed' or even for each group individually after all text answers for this group have been reviewed.

**Comment by karyon** [comment]
we noticed that for #612 and #1131, a random group ID is sufficient and thus we don't need to weaken anonymity. a notification for the user that during review the answers will be seen as a group should still added to the tooltip that explains the respective buttons.

I think we should implement any of those first. It will include a lot of the work required for #1132 while not weakening anonymity and will give us a nicer base for discussing #1132.

for #1132, there are several options:
1. Implement as proposed by using a using a hash of the user and the respective contribution and question as group id. That is of course just an obfuscation and anonymity is weakened.
2. Use the users password. This will require additional work and inconvenience for the user because of password changes (or we haven't found the proper way around that yet)
3. Use some other weak password provided by the user, something like "first two letters of your mothers name", "month of your fathers birthday" etc. as seen in some survey programs. Of course, social engineering etc. but i'm not sure we need to go this far and to protect against targeted attacks against individuals. Another downside: This is either opt-in (and will be rarely used because of that) or will be slightly annoying for users.
4. Do option 1, but let the user opt-out, disabling the feature for that user for the respective course. That would give the previous level of anonymity to those who want it, and for the others a nice feature at the expense of lost anonymity in case of a database breach during the evaluation period.

in case of option 1 or 4, we should not forget to exclude this hashing data from the admin view to actually deliver on the promise that de-anonymization can be done only with database access.

**Comment by PFischbeck** [comment]
A note on option 4: if only one user opts out for a certain course, he (and his single comment) can be identified, since his comment is the only comment for a question that doesn't have a grouping id. This means that a user who opts out for privacy/anonymity reasons might still be at a disadvantage due to this feature and can be identified.

**Comment by He3lixxx** [comment]
I talked to the people who run the HPI's OpenID Provider. They can't really provide any help here. Seems like our best bet is using emails.
Proposition: We want to generate a random group id for #612 and #1131 anyways. Users can get a checkbox at the bottom of the page. If selected, they get an email with their group id (which makes the group id their 'secret'). The default could be whatever the user had selected last (opt-out on the first time). The email contains a link which leads back to the evaluation page where the user can edit his / her answers. The admins should not be in the bcc of this email.

**Comment by janno42** [comment]
Closing, because we didn't find a good solution during the last 5 years that ensures anonymity and doesn't require users to download a key, remembering a password, etc.
The use cases seem not to be worth the trouble.
