### ISSUE TITLE
It is possible to reconstruct the author of all text answers and some rating answers

### ISSUE THREAD

**Issue by karyon** [e-valuation/EvaP#1384]
Follow-Up to https://github.com/fsr-de/EvaP/issues/1335.

Postgres saves the transaction ID of every tuple inserted into the database (xmin of the system columns). Since the vote operation by design is one transaction, and that transaction saves both all the answers and the addition to the `voters` table, there's a direct link between authors and all their answers.

For rating answers, this is not entirely solved by the use of aggregating counters: the tables in postgres are insert-only, that means old versions of those counters stay in the table at least until the next VACUUM. So you just need to diff the version in question with the previous version. Though i couldn't find how to access such old tuples, it would be nice to not have them. But in any case, the comments are the bigger problem.

Possible solutions from less-bad to bad:
* ~~CLUSTER + VACUUM might just work. We should verify what happens when inserting a tuple with a UUID PK, then clustering the table, and then vacuuming. In case the CLUSTER has it's own transaction (it might not, since it has ACCESS EXCLUSIVE on the entire table, i dunno?), it might create new versions of the reordered tuples just like other updates do. In my naive understanding, since our answers have random PKs they will usually not go into the last page of the table and will have to be moved by the next CLUSTER (as long as the [fillfactor](https://www.postgresql.org/docs/12/sql-cluster.html) stays at 100%). Combined with a VACUUM, that might be it already. So maybe we don't even need to change anything! :D but we should verify.~~ CLUSTER does not change the xmin even if the tuples move.
* When inserting votes/comments, touch existing votes/comments of the same evaluation (e.g. flip a dummy boolean, or maybe an UPDATE with no changes is enough). VACUUM periodically.
* Periodically touch all votes/comments of the active semester. VACUUM afterwards.
* We could aggregate all comments for a question to one large text in the database with some separators, but since old versions of this large text would be kept by postgres at least until the next vacuum, that doesn't seem like a full solution. Also, we'd still have the order of when the user added their comment, which would be nice to not save as well. Also, we'd probably need to shuffle the order of the comments within that large text, and that won't help with questions that receive only one comment...
* [On stackoverflow](https://stackoverflow.com/questions/58758713) people suggested to put our voters-table and the answers on different databases. I think that does not solve anything, since the consecutive transaction ID sequences on both databases still allow for a full correlation of the two tables.
* Putting the inserts of the vote operation in different transactions doesn't really solve anything since transaction IDs are consecutive. Also we'd lose the transaction guarantees.

**Comment by He3lixxx** [comment]
(Also putting this here for reference: https://news.ycombinator.com/item?id=22777260)

**Comment by He3lixxx** [comment]
If we do any changes, it would be nice to have some detailed information about all the stuff we do to get rid of data on a wiki page and comments in the code linking that page. Currently, this is what comes to my mind and what we have had in the presentations
- Transparency: Showing who will be able to see a text answer on the evaluation page
- Warning on low number of participants. Option for the first voter to discard their text answer if no other participants vote.
- Don't handle passwords at all
- using UUIDs instead of ids on `RatingAnswerCounter` and `TextAnswer`
- regular CLUSTER by id to fix physical order on disk (https://github.com/e-valuation/EvaP/wiki/Installation#database-clustering)

stuff not yet implemented:
- using VACUUM / whatever to get rid of the transaction ids in the tuples that also give away the insertion order (not done yet - this issue)

Stuff that is out of our reach:
- Making sure that the machine really overwrites stuff in memory and on disk. This includes backups that may be done of the server vm.


Someone on ycombinator suggested to do the bitflip-thingy on all changes instead of regularly. I think it's worth considering, but doing it once a day is probably enough for us and it might stress the servers during the period where most of the evaluations are active.

**Comment by karyon** [comment]
There is https://github.com/e-valuation/EvaP/wiki/Data-Economy, which at least mentions the UUIDs.

**Comment by karyon** [comment]
Exactly!

**Comment by He3lixxx** [comment]
Okay, so, check list for myself (first three should occur when student POSTs their answers to the server):
- When creating the `RatingAnswerCounter`s, make sure that they are all created with the same xmin (-> disallow finding out what the first voter voted for)
- When increasing the `RatingAnswerCounter`s, make sure that afterwards, all `RatingAnswerCounter`s for the same evaluation have the same xmin (otherwise attacker could deduce the last vote)
- When saving a TextAnswer, make sure that all other text answers for the same evaluation get the same xmin (so far applies to insert only, since this is the only timestamp conveying author information).
- Make sure the database runs vacuum periodically (I think it should be the default behavior, but check again. We might want more regular intervals -> maybe cronjob - it could also send out an email if there are old tuples that were not deleted).

Both TextAnwer and RatingAnswerCounter inherit from our abstract Answer class. We could just override the `Answer.save` method to do the xmin updating for all the columns. However, if "user" code directly uses insert, update, bulk_insert or bulk_update, this will not be caught (and there might be other cases?). Keep in mind that with the TextAnswer review logic, we probably have quite some save / update statements there that do not need this protection, but I don't think having it there would be a problem(?). 

Or, we could make the "critical" operations do the necessary stuff inside one transaction in the views (when saving the answers).

A shotgun approach could be to add a (database trigger)[https://www.postgresql.org/docs/current/sql-createtrigger.html] to all subclasses of `Answer` that makes sure that all rows have the same xmin. I'm unsure of performance hit here, especially if we update all rows instead of only the ones for the current question. Doing more complex stuff this way (seems to be painful)[https://www.postgresql.org/docs/11/sql-createprocedure.html]

While I feel confident that I can apply the necessary changes for the current codebase, I feel unsure about how to prevent similar issues from occurring in the future. Ideally, we would want to make sure that all xmins for all Answers are always identical(?). However, if someone adds a new view that saves some kind of user answer, I don't see how tests could catch that. Would we want to make access to save-methods for `Answer` classes more secure? Some kind of "If you write an Answer to the database, you have to confirm that you know what you're doing? I don't see any simple and effective solution here. Then again, the probability of someone introducing a new code path that saves user answers to the database is fairly small I think.

Any thoughts @janno42 @karyon @felixrindt @pixunil?

**Comment by karyon** [comment]
For the first bullet point i think we don't need to write any specific code I think. The counters are always created with a value of zero, and then increased, so if we do the second bullet point and write all the xmins on every increase, that's good enough.

doing the xmin update inside save() would be a little wasteful, since it would be done dozens of times per POST.

Personally I would keep this simple. E.g.: after the votes have been written but while the transaction is still open, write to all the Answers of the current Evaluation. Since Answer doesn't have its own table, we'll probably need one update query per Answer type, I think that's fine as well.

I wouldn't worry about missing a new code that adds answers. We've never done that for multiple years, we don't have concrete plans to do that, and if that ever happens, we'll hopefully talk long enough about anonymity implications of that new feature to remember this.

Similarly, in the future a new Answer type might be added that needs an additional update query, but I wouldn't worry about that either.

**Comment by He3lixxx** [comment]
Todo when the PR is merged:
- update https://github.com/e-valuation/EvaP/wiki/Data-Economy
- implement some vaccum strategy for the server (discuss)
- document what we have done (cron setup or whatever)

**Comment by He3lixxx** [comment]
A quick inspection on production said that autovacuum was enabled, however, runs very irregularly (for some tables, it hasn't run for years). A simple `VACUUM;` cleared all dead tuples in all tables. We decided that this is enough for our case, so we simply updated the cronjob that currently runs `CLUSTER;` once a day to also vacuum all dead tuples.

I updated https://github.com/e-valuation/EvaP/wiki/Data-Economy and https://github.com/e-valuation/EvaP/wiki/Installation.

Doing that, I noticed that https://github.com/e-valuation/EvaP/wiki/Installation#database-vacuuming-and-clustering explicitly sets the tables that need to be clustered. If we add a new question type, it needs to be added there, too.
What do you think about annotating that to the test line we have here? (I'm slightly in favor)
https://github.com/e-valuation/EvaP/blob/00886de1d14d37b40bd8167dc7d4d911e6aa0f23/evap/student/tests/test_views.py#L308

However, I think all content of this issue is now solved.

**Comment by karyon** [comment]
> What do you think about annotating that to the test line we have here? (I'm slightly in favor)
Also slightly in favor :)

Great work overall!
