### ISSUE TITLE
Select2 issues

### ISSUE THREAD

**Issue by pixunil** [e-valuation/EvaP#1461]
There are some issues with the select2 input. Some of those might be an actual bug in the dependency, some points might be changed on our side.

- You can not <kbd>Tab</kbd> into the select2 input
- An entered value which was not accepted by pressing <kbd>Enter</kbd> will get discarded when losing focus
- Invalid select2 inputs don’t have the red outline like other fields
- When deleting an item with <kbd>Backspace</kbd>, the text of the item can be edited. However, the input is initially too small so that not all letters are displayed.
- When deleting an item on select2’s with tags (like import names on degree and course type) and re-adding it, it sometimes appears twice afterwards

**Comment by pixunil** [comment]
As mentioned earlier, I hope that some points get resolved with a newer version of select2.
I would suggest to wait for the full release of 4.1, as it is currently in [beta-1](https://github.com/select2/select2/releases/tag/4.1.0-beta.1) and could get released soon.

**Comment by He3lixxx** [comment]
We've updated select2 to 4.1.0-rc.0 in the meantime. This is the current situation:

### The good stuff:
* Tabbing into select2 inputs is now possible
* On tag inputs, starting to type a new tag and then clicking somewhere else will add the text so far as a tag if `selectOnClose` is set to `true` ([documentation](https://select2.org/configuration/options-api))
* The red outline for inputs currently doesn't even appear for non-select2ed-selects. It is set by us in [components/_forms.scss](https://github.com/e-valuation/EvaP/blob/main/evap/static/scss/components/_forms.scss#L3), and we only apply it to DOM nodes with the class `form-control` there. However, only set this class for [input](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/templates/django/forms/widgets/input.html) and [textarea](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/templates/django/forms/widgets/textarea.html) widgets, and not for [checkbox](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/templates/django/forms/widgets/checkbox.html) or [select](https://github.com/e-valuation/EvaP/blob/main/evap/evaluation/templates/django/forms/widgets/select.html) widgets. According to the bootstrap doku, it [would be correct to also set it for select widgets](https://getbootstrap.com/docs/4.0/components/forms/#form-controls). Then, normal select-fields correctly the red outline. However, inheriting the `form-select` class into the select2 container through the `selectionCssClass` option breaks rendering again, because then bootstrap and select2 fight about how the element should look. I'd argue we could add a second selector to `components/_forms.scss` here to handle the select2 case (using `.select2-selection`). Then, it works.
* Tag input, going into element-edit mode using backspace works for me, nothing is truncated (was their issue 3297)

### The bad stuff
* Select2 Issue 3498: Deleting an item and re-adding it adds it two times. Very likely a select2 bug: I could reproduce this on the course type page:
    * Load the page, click on any tag input. Press backspace (goes into editing mode), then enter -> Element is added twice.
    * It's also added twice when clicking on the "x"/removal button and then adding the same element again.
* Select2 Issue 3335: In multiple selects with `allowClear`, pressing backspace may clear the whole thing instead of just removing the last entry (happened to me on the userprofile edit page, in the CC-users field: Add 3 entries, press backspace -> all gone
    * Their issue presents several workarounds
* Select2 Issue 6115 (our #1638): If focus is on a select2-dropdown, the page is scrolled away, and then the focus changes (e.g. by the user clicking somewhere else), select2 causes the page to scroll so that the select widget is in view again.
