### ISSUE TITLE
Notify contributors when their free text has been deleted

### ISSUE THREAD

**Issue by LinqLover** [e-valuation/EvaP#1505]
I know that free texts submitted by contributors are stored anonymously and cannot be traced back to an individual contributor. Yet, it would be an option to assign private keys to every contributor and attach these keys to their free texts. After the evaluation has been published, a contributor could check whether it contains their private key.

I am not an active developer of this project, nor do I have any capabilities for designing such a feature. Just wanted to share this idea with you. I think it would be great if, despite the presence of any - inevitably - intransparent filtering process, you had the option to validate that your feedback texts have actually reached the evaluated people!

**Comment by janno42** [comment]
Thanks for your input! This request is quite tricky because it involves many different interests and technical problems. As this touches the way evaluations will be handled specifically by one committee, we can't comprehensively discuss it solely from the technical side on GitHub. The "political" decision has to be made by the student representative group.
From a technical perspective, it would be quite difficult to implement. We can't simply attach some kind of information to the text answers that can be linked to the authoring students because that would violate anonymity. The only (simple to implement) solution I can imagine right now would be to show students a list of the ids of their text answers once they have submitted the questionnaire and somehow distribute all ids of text answers that have been deleted after publishing the results. However, students would have to store quite a large number of very long ids to compare them with those announced and that's not feasible.
Usually (when having to deal with the text answers at all, which happens scarcely in contrast to the thousands of text answers given each semester), text answers won't even be deleted whole, but only small parts will be omitted. Then, it's even more difficult to transport that information.
We are very much in favor of transparently giving information about what's happening how and where, when not having to give up other principles as anonymity. So a discussion with and within the student representative group just began about how we could deal with the problem of hard insults in text answers in the best possible way. This will probably result in future GitHub issues.
