### ISSUE TITLE
Users might receive a stale datagrid.js / Rethink JS asset handling

### ISSUE THREAD

**Issue by karyon** [e-valuation/EvaP#1515]
datagrid.js (and also text-answer-warning.js from #1513) is currently served from the static directory without being processed by django-compressor. apache serves those files with a cache expiry date of `access plus 1 month`. I suspect that when we modify datagrid.js, clients might use an old cached version for up to a month.

django-compressor doesn't play well with ES6 modules I'm afraid. There's a PR open so you can output a <script type="module ...>, but this would even help with the `import from ...` style we're currently using.

What if we removed django-compressor? Here's what we use it for and what we could do instead:

1. concatenation
    * instead: enable HTTP/2. we should do that anyways, and concatenating assets is not a best practice with that anymore.
2. minification
    * instead: do nothing. our dependencies are minified either way, and the couple KB of JS that we hand-write might as well go without minification.
    * while we are at it, we could enable brotli. ideally, we would pre-compress our static assets and configure apache to use those.
3. cache-busting (appending hashes to filenames of the assets)
    * Instead: use [ManifestStaticFilesStorage](https://docs.djangoproject.com/en/3.1/ref/contrib/staticfiles/#manifeststaticfilesstorage), which does the same
4. scss processing
    * Instead: (not so sure about this one) we add a `./manage.py run scss [--watch]`, which compiles the scss into static_collected. it must be called whenever collectstatic is called, and when editing scss files. I'm not 100% sure that would even work, does django's development server actually looks into static_collected...?
    * Or we keep django-compressor specifically for scss files, but that feels kind of wrong.

Any other ideas/input?

**Comment by pixunil** [comment]
First, my input to your points:

1. concatenation
    - I agree with you that concatenating will be rather obsolete through HTTP/2. I haven’t researched a lot on this topic, but afaik this can be achieved by a better reuse of connections. In a second stage, we could make use of Server Push, which may need additional configuration.
2. minification
    - I would also add that there exists minifiers / bundlers for JS, which could also make some polyfills automatically (if necessary)
3. cache-busting
    - For appending hashes, this looks like a sensible alternatve, but I think we may want an entirely different approach as changing names doesn’t work nicely with `import from`
4. scss processing
    - I’m using a [management script](https://gist.github.com/pixunil/f72df8f3e5e978f4e9881a2f508f4a44) for compiling the scss during development on my other Django project and hadn’t any issues yet. It basically calls `sass --watch static/scss:static/css`. The `static/css/ directory is ignored via `.gitignore` (and at least in my set-up, Django’s development server looks into the static directory). Cons for this approach: I have to open an additional terminal tab, Pros: The changes are detected automatically and I get more information what is compiled when.
    - For release, I use `sass --style compressed --sourcemap=none` which also does minimize the css. Just as a little input what’s possible here :)

However, I would also draw focus on how we have JS in our sources:

- **J1** External dependencies, mostly minified, in `static`. They are needed nearly everywhere and are included in `base.html`. Bundling them in a big file is also a sensible approach imo. (Example: `jquery-2.1.3.min.js`)
- **J2** Custom scripts as assets in `static`. These are included only in individual sites. (Example: `copy-to-clipboard.js`)
- **J3** Custom modules as assets in `static`. The idea behind this was to have the common parts in a static external file which can be imported. However, the import statements really don’t appeal to me how they look atm. So if you  (Example: `data-grid.js`)
- **J4** Django templates `.html` with inline JS. I think these are fine for some little glueing code, but some code e.g. in `base.html` is rather static but will be sent every time with no possibility to cache.
- **J5** Django templates `.html` which include a `<script type="text/javascript">` and possible interpolate source code. I view them as some kind of legacy, because linter support for JS + DTL is rather poor and it doesn’t support caching as nice as static assets. (Example: `sortable_form_js.html`)
- **J6** Django templates `.js` which are included in other templates. Similar to **J5**, these have rather poor linting support because of interpolation with DTL. (Example: `quick-review.js`)

If we refactor some of the legacy approaches (**J4**, **J5**, and **J6**), we will end up with more static assets, so I thought this could be relevant for this discussion.
As I understood, we currently don’t benefit of Django compressor's features for **J2** and **J3**, as they aren’t surrounded with `{% compress js %}`. As **J2** and **J3** are currently in a minority (`copy-to-clipboard.js` + `data-grid.js`) I don’t see an active need to replace compressor for the vast majority of our files.
When I’m understanding the issue correctly, the only part where compressor isn’t integrated easily would be for `import from` statements for **J3**. Well, I didn’t think of cache busting before, and I would say that appending file hashes doesn’t work nicely with modules (for the inline javascript glue code we can use DTL, but when we would import modules in `static` itself, this would get complicated).

When we don’t want to do cache busting with appending hashes to file names, I stumbled across [this SO](https://stackoverflow.com/questions/47675549/how-do-i-cache-bust-imported-modules-in-es6). This may need some more research, but the first proposal is to send a `ETag` with the hash of the file. This would require a different server configuration but abstracts the problem away from our application and doesn’t meddle with file names.

Puh, I hope you got not tired reading my wall of text. But now I got the opportunity to familiarize myself more with these topics :)

**Comment by karyon** [comment]
Re cache busting, iirc you're doing `import from {% static some/file.js %}` anyway. If i understand correctly the point of the static tag and the manifest storage is to insert the hash-appended filename so I would hope that this just works.
I think even importing a module from another module might work with {% static %}, the docs talk about the storage code doing multiple rounds of hashing until they settle. Though it probably would break linters and syntax highlighting again, hm...

Your scss handling sounds nice.

The ETag prevents transferring an unchanged file, but the client still requests it, so the network roundtrip is not avoided. The cache busting filename + expiry date allows the client to not request the file in the first place, which imo is a very elegant solution. Not sure though whether it makes any difference in practice. Production actually sends etags with the assets, that seems to be the default in apache.

I agree that J4, J5, J6 are not ideal and could be refactored.

**Comment by pixunil** [comment]
Wow, after your explanation I see how fancy the cache busting mechanism is – having no request at all is a clear winner.
I read the documentation of [`ManifestStaticFileStorage`](https://docs.djangoproject.com/en/3.1/ref/contrib/staticfiles/#manifeststaticfilesstorage) more carefully then the first time, and would like to point out that we could configure a pattern for `*.js`, which matches on the [`import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) statement. That way, we don’t need the power of DST (so no `{% static %}` in a possible `static/js/module-which-uses-other-module.js`).

Either way, the `import` statement in JS accepts strings, so as long we don’t use the same quotes, we should be safe here. The only downside I experience with PyCharm is that all imported items are not resolved and get a weak warning.
I know, not everyone is using a IDE (and it shouldn’t drive decisions), but I get full inspections (jump to definition, code completion, etc) when using `import … from "/static/js/module.js"` and marking the directory `evap` as directory above `static` as resource directory (Also works with `import … from "/js/module.js"` and `static` as resource directory).

```javascript
// For code inside <script>, we generally have DST available and can use {% static %}
// Only issue here is that IDE’s don’t seam to make the connection to the js file
import { TableGrid } from "{% static 'js/datagrid.js' %}";

// Other option for code inside <script>, if we somehow can meddle with the module url like one would do for static assets
import { TableGrid } from "/static/js/datagrid.js";

// For code in static assets, the added hashes should be added transparently by the ManifestStaticFileStorage
import { TableGrid } from "datagrid.js";
```
-----

So~ after mentally stamping a “Theoretically Approved” on the “Big, future-proof solution”, back to your entry concern:

- If Django compressor somehow can provide an url for a compressed + cache busted file so we can write `import … from "{% compressed "js/module.js" %}"`, this would be the minimal invasive approach
- Otherwise, `ManifestStaticFilesStorage` looks like it would fulfill our needs for module assets. (concatenation and minimization isn’t important here I think). However, I can’t see a possibility to turn `ManifestStaticFilesStorage` as `STATICFILES_STORAGE` specifically only for a subset of `static`. So when we don’t want to fully migrate to the “Big, future-proof solution” immediately, we have to check whether having compressor (for the common bundle of JS) and `ManifestStaticFilesStorage` (for other static files) works fine. I can at least confirm, that when `DEBUG = False`, `{% static %}` appends the hashes correctly

**Comment by karyon** [comment]
Seems like I misunderstood how the ManifestStaticFileStorage replaces URLs, thanks for clarifying. Also good to know we could configure it to also detect and replace `import` urls (though the subclassing approach feels a little clunky to me). I'd not do it until we need it (that is, until we want to import a module from another module).

Currently I don't see any way to make `import { foo } from "/bar/baz.js";` "just work" including caching, cache-busting, and IDE support. Using {% static %} and losing IDE support is what I'd suggest (and that also the status quo, isn't it?)

I wouldn't worry about not fully migrating everything and simply fully migrate everything :)

**Comment by pixunil** [comment]
After merging #1529, HTTP/2, Brotli are still unaddressed. But at least the Javascript shouldn’t be cached for a very long time now.

**Comment by He3lixxx** [comment]
> After merging #1529, HTTP/2, Brotli are still unaddressed. But at least the Javascript shouldn’t be cached for a very long time now.

#1529 has removed django-compressor completely, established the ManifestStaticFilesStorage, and uniformly changed all js imports to the form
```js
import { TableGrid } from "{% static 'js/datagrid.js' %}";
```

Is the "Users might receive a stale (whatever)" still relevant? From what I can see on production as an average student (couldn't check the vote page), every single static file now uses a concatenated hash.

If it's not, and we're just talking about enabling http2 or applying optional minification or compression to static files, I'd like to either open a new issue for that or at least change the title here. Currently, the title and the first post reads as if we are expecting site failures for about a month after an update.

**Comment by He3lixxx** [comment]
Production logs indicate that we don't have any accesses on files without hashes, so I'm closing this for now and making a new issue for http2 and brotli.
