### ISSUE TITLE
Navbar CSRF caching broken for entering staff mode

### ISSUE THREAD

**Issue by niklasmohrin** [e-valuation/EvaP#1530]
Steps to reproduce (on master, after reloading test data):

1. Log in as evap
2. Enter and leave staff mode
3. Log out and log in again
4. Try to enter staff mode

This will throw a 403 CSRF something error and people in Discord concluded that it is because the navbar is cached across logins. Clearing this cache on logout was proposed. This is reset when reloading test data again,

**Comment by He3lixxx** [comment]
We're currently considering dropping the navbar cache alltogether, since it caused quite some bugs over the time and we need a lot of cache invalidation all around the codebase.  Thus, it would be nice to know how much performance we actually currently gain from the cache (originally added in https://github.com/e-valuation/EvaP/pull/598). We suspect that one of the main impacts might be that for n permission checks, we currently do n queries (check out the properties `is_manager`, `is_reviewer` and `is_grade_publisher` for examples). We should be able to prevent this by prefetching the groups of a user and using the prefetched values. Or, we could overwrite the cached_properties (although I consider this more likely to cause bugs in the future, as it is hidden behaviour).

**Comment by karyon** [comment]
prefetching wouldn't work directly as filter queries are used, but using the newly added is_prefetched would work (so prefetching all the user's groups, and then iterating through the list if it's prefetched instead of doing the filter query)

**Comment by karyon** [comment]
Seems like we had the session ID in the cache key at some point but removed it: https://github.com/e-valuation/EvaP/issues/1208

**Comment by pixunil** [comment]
I’ll also add that a Csrf error is thrown when I’m logged in a different browser:

1. Log in as evap (in browser A)
2. Enter staff mode
3. Log in as evap (in browser B)
4. Try to leave staff mode

Due to the similarity with the issue, I guess that this error-case is also covered by the defect
