### ISSUE TITLE
Dictionary merge error in course importer

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1711]
the following code wants to merge error dicts. however, this fails with a `TypeError` (`unsupported operand type(s) for |: 'str' and 'str'`) in `merge_dictionaries_of_sets`.
https://github.com/e-valuation/EvaP/blob/32caa9d799a938f88fa49940b16f4f44bd89d431/evap/staff/importers.py#L413-L415

reproduce by importing a file with two entries: two participants having the same course that differs in its degree (e.g., `BA` and `MA`) and having another error (e.g. grade `ungraded` instead of `no`).

**Comment by niklasmohrin** [comment]
This happens because the `errors` aren't actually shaped like this function assumes, looking at `EvaluationDataFactory`, we can see that the `is_graded` and `course_type` keys actually map to single strings, not a `set` like `errors["degrees"]`.

We could fix this by either only merging the keys that we know are `set`s, or make all value types `set` too (and add a type hint?). At first, I though that since there could be multiple wrong course types or `is_graded`-strings for the same evaluation, we should do the second approach. _But_, since this error only happens if the two rows are `equal[s]_except_for_degrees`, the first is probably more appropriate.
