### ISSUE TITLE
Investigate Github Action caching

### ISSUE THREAD

**Issue by niklasmohrin** [e-valuation/EvaP#1749]
One can cache certain directories in github actions. For Python, caching the entire installation is used (including all the `site-packages`), so that wheels don't need to be rebuild. Additionally, the download could be faster. We should investigate how much there is to gain.

**Comment by He3lixxx** [comment]
Agree as long as its not much hassle (causes errors, lots of configuration)

Installing python requirements takes ~15s on a github runner, installing the node dependencies takes ~25s -- this is what we could gain, right?

Our slowest actions currently are
[Test + Coverage](https://github.com/e-valuation/EvaP/runs/6247385090) (~2:25min) with
- 30s container setup (waiting for postgres to start)
- 17s installing dependencies
- 1:20min running tests

[Backup process](https://github.com/e-valuation/EvaP/runs/6247384862) (~2:45min)
- 30s container setup (waiting for postgres to start)
- 16s installing dependencies
- 35s load testdata
- 24s backup
- 46s loading that backup

so it seems to me that the 15s for installing dependencies wouldn't really be the most relevant optimization -- but still, we could do it.

In theory, backing up and restoring the database state can be done in ~1s (pg_dump can create an sql file that can be loaded back). It's so slow here because django does this one-object-at-a-time and does a lot of extra work that we don't actually need. We could consider changing our format to the .sql files created by pg_dump, for the backup during an upgrade as well as for our test_data.json. (Somewhat related: There was https://github.com/e-valuation/EvaP/issues/333 8 years ago :D)

It doesn't really make sense to wait for postgres to start, only to _then_ start installing dependencies. We could make that step parallel (don't know if this is specifiable in github actions?)
