### ISSUE TITLE
Use django's generic views to reduce boilerplate code

### ISSUE THREAD

**Issue by richardebeling** [e-valuation/EvaP#1754]
Django provides a few generic views. At first glance, it looks like using them could reduce boilerplate code. The [`LoginView`](https://docs.djangoproject.com/en/4.0/topics/auth/default/#django.contrib.auth.views.LoginView), [`FormView`](https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-editing/#formview), [`DeleteView`](https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-editing/#deleteview), [`CreateView`](https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-editing/#createview) and [`UpdateView`](https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-editing/#updateview) seem to be the most relevant for us.

The login view implements some kind of redirect logic which might allow reducing or removing our custom redirect logic, but I don't know whether it would play well with multiple login methods (key, pw, oidc). The other views should remove overhead for delete/create/update views, iirc some of our views are boilerplate-only, so they should be applicable.

**Comment by niklasmohrin** [comment]
Seems to be a very deep rabbit hole of Django best practices that we could adapt reaching into the core of EvaP:
- naming of template files: for a potential `class SemesterCreateView`, the default name would be `semester_create_form.html`, our naming scheme is `staff_semester_create.html`. There is builtin functionality to change the suffix to `""` instead of `"_form"`, but there is nothing for the `"staff"` prefix
- the default handling for create and update (and form?) views is to redirect to the model's `get_absolute_url`. I suppose we could adapt to use this over `reverse(..., args=[thing.pk])` and `{% url ... %}` when possible
- make our `@*_required` decorators work with class-based views (or find a better way, for example check out [`UserPassesTestMixin`](https://docs.djangoproject.com/en/4.2/topics/auth/default/#django.contrib.auth.mixins.UserPassesTestMixin))

Further todos I stumbled upon:
- There is `user_passes_test` in both `django.contrib.auth.decorators` and `evap.evaluation.auth`. The latter seems to deviate by returning 403 instead of redirecting, I think our version's comment could mention the other to make it clearer why we have our own
- figure out / fix typing with django-stubs ?

However, I still think that this could be pretty cool. There are some places where it would really fit, for example semester create and edit are very similar and simple:
```python
class SemesterFormViewMixin(ModelFormMixin):
    model = Semester
    template_name = "staff_semester_form.html"
    fields = ("name_de", "name_en", "short_name_de", "short_name_en")

    object: Semester

    def form_valid(self, form) -> HttpResponse:
        response = super().form_valid(form)
        if "short_name_en" in form.changed_data or "short_name_de" in form.changed_data:
            update_template_cache(self.object.evaluations.filter(state__in=STATES_WITH_RESULT_TEMPLATE_CACHING))
        return response

    # TODO: move to get_absolute_url, which is the default
    def get_success_url(self):
        return reverse("staff:semester_view", args=[self.object.pk])


# @manager_required # TODO
class SemesterCreateView(SemesterFormViewMixin, CreateView):  # type: ignore
    pass


# @manager_required # TODO
class SemesterUpdateView(SemesterFormViewMixin, UpdateView):  # type: ignore
    pk_url_kwarg = "semester_id"
```
The above is equivalent to the `SemesterForm` combined with the `semester_view` and `semester_edit`. One thing I found interesting is that the breadcrumb on the semester edit page still worked. Digging into all the implementations of `get_context_data` in the inheritance shows that at some point we get `semester` set because we have `model = Semester` (we could overwrite it by setting `context_object_name` on our class). It took me a moment to figure out what was going on because the inheritance hierarchy is a bit complicated - this could be difficult to see through for new contributors. Or maybe it is equally difficult to what we currently have :shrug: 

What do you think @janno42 @He3lixxx ? Unless we want to step back from the idea, I would keep working on this :)

**Comment by janno42** [comment]
For me using the generic views where possible without unreasonable effort sounds great.
