### ISSUE TITLE
Remove sass + ts compilation from ./manage.py run

### ISSUE THREAD

**Issue by He3lixxx** [e-valuation/EvaP#1783]
These slow down starting the development server.

For developers actually changing TS or SASS files, they are not helpful enough, and those will likely start a `--watch` job anyway. We can simply provide a ´./manage.py watch` script for this use case.

For anyone else, they simply slow down the development server startup, which is a bit annoying.

Opinions?

**Comment by niklasmohrin** [comment]
I thought about this again and just removing compilation could really do us more harm than good. Before, we came to the conclusion that we can spare newcomers the burden of thinking about compiling ts and scss by doing it for them in the provision script, but what happens when they pull updates from main that change these files or add new ones? This could lead to great confusion / frustration for them and us. Maybe the solution we want is opt-in behavior, like a `--no-compile` / `--fast` / `-f` flag that skips the two and that we can tell people to use once they are comfortable with the project setup / annoyed by the long startup time. What do you think?

**Comment by He3lixxx** [comment]
Good point. Similar things are true for dependencies (npm, pip), but those probably change less frequently.

Honestly: I'm lazy and don't want to type `-f`. I think the default should be fast.

I would be fine with starting the jobs in the background. They could even be `--watch` jobs running the background. I think the main reason we didn't make them --watch jobs is because their output was mushed together, but honestly, if you're editing TS and you want clean output, I think then you could just `./manage.py run --no-watch` and `./manage.py ts compile --watch` in another console.

**Comment by niklasmohrin** [comment]
Haven't thought about background jobs yet, how do you feel about starting a background process that compiles the files once? This way, we don't get (much) output mangled in the python output
