### ISSUE TITLE
Inverted Likert Scale

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#1963]
We currently have the following likert scale, ranging from "Strongly agree" (positive) to "Strongly disagree" (negative):
![image](https://github.com/e-valuation/EvaP/assets/1781719/bf194a23-0776-47b4-855d-bb59bf877b63)

The connotation is shown by color. In the results computation, grades reach from 1.0 ("Strongly agree") to 5.0 ("Strongly disagree").

For some questions, an inverted scale would be a better fit (e.g., "I felt overwhelmed by the workload"). Currently, these questions have to be rephrased ("I did not feel overwhelmed ...") which is not optimal.

An inverted likert scale should be introduced, using the range from "Strongly disagree" (green, 1.0) to "Strongly agree" (red, 5.0).
The current 'LIKERT' scale should be renamed to "POSITIVE_LIKERT" ("Positive agreement") and the new scale will be "NEGATIVE_LIKERT" ("Negative agreement").

**Comment by He3lixxx** [comment]
Additional discussion by @janno42, @niklasmohrin and me regarding possible confusion of users while voting, possibly causing the wrong answer to be selected in the end:

* While the connotation "positive" and "negative" is clear from the colors, users might have two different interpretations:
    * User A might think that "green" = "left" = "yes", an affirming option regarding the prompt / question.
        * This is consistent with what most random internet surveys / questionnaires use, in a typical "Agree" to "Disagree" likert scale, where the system does not know the connotation / semantic meaning of an answer.
    * User B might think that "green" = "left" = "good" / "optimal", the positive option in the matter.
        * This is consistent with the "this is good" and "this is bad / must be changed" notions, as can be the intuitive understanding of EvaP result pages and as is an widespread connotation of the colors red and green.
    
For the question "I felt overwhelmed by the lecture",
* User A thinks that "green" = "left" = "yes", because colors and position imply agreement to the question.
* User B thinks that "green" = "left" = "no", because colors and position imply a positive semantic meaning.

This is amplified by the fact that long-time users probably don't actually read questionnaire introductions or button texts anymore.

We considered inverting the order of the buttons for inverted questions. This is
* inconsistent with yes-no-questions so far
* inconsistent with how the results would be displayed. Also swapping the color order on result bars would lead to a confusing visual appearance.
* possibly helping users realize that their selected answer does not mean what they thought it meant. This might not work with color blind users.

* We considered adding happy and sad smileys to the questions, but they would add a lot of clutter to the student vote page while the happy and sad smiley look very similar.


For now, we think this simply is a hard problem with no optimal solution. We decided to add the feature here for now, but also add a warning icon in #1969. We want to make staff users aware of the issues with this kind of question to make sure they understand the possible negative impact.
