### ISSUE TITLE
Remove degrees and course types from contributor export header

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#2002]
In the contributor results export file, the header includes "Evaluation", the contributor's name, and all existing degrees and course types.
Instead, only "Evaluation" and the name should be exported.

Exports other than the contributor export should not be modified.

**Comment by richardebeling** [comment]
@janno42 With the default testdata, both users `evap` and `contributor` currently only get an empty excel file when pressing the "Export results" button on the contributor index page (which is the button I think this issue is about, right?). This hindered progress with this issue, as it makes it hard to understand the issue (as there is no data row with these headers).

Do we want to update test data to include some results for the user `evap` by default?

@Tillbtn @finger813 Executing the following lines in `./manage.py shell_plus` already made some data show up for me, maybe that's enough for you for now:
```
from model_bakery import baker
e = Evaluation.objects.filter(name_de="Softwarearchitektur").first()
u = UserProfile.objects.filter(email="evap@institution.example.com").first()
c = baker.make(Contribution, evaluation=e, contributor=u)
```
It looks like it isn't necessary that there are any actual results for the contributor.

**Comment by janno42** [comment]
You can login as `responsible@institution.example.com` to have useful test data.
@richardebeling Adding some data for `contributor` is something we can do in addition.
