### ISSUE TITLE
Remove underlines from results evaluation lines

### ISSUE THREAD

**Issue by janno42** [e-valuation/EvaP#2115]
On the results index and results detail pages, the text in evaluation lines is underlined when hovering. The text should not be underlined on hover state.

![image](https://github.com/e-valuation/EvaP/assets/1781719/cd01793a-0679-4c8c-bbbf-365ea6df6c03)

**Comment by richardebeling** [comment]
This broke in #1771 / baaa7dd5c55749a9fa17f5ad1f14e2e2bd4fec53 on main

Bootstrap applies `text-decoration: underline` to `a:hover` in `_reboot.scss:247`. Before that commit, our override in `_grid.scss:55` to have `text-decoration: none` was more important. After the commit, the bootstrap rule has become more important. Seems like both rules have identical specificity (one class, one type), and we unintentionally changed their order due to some additional includes in that PR.
