### ISSUE TITLE
Creating Superuser fails on a fresh install

### ISSUE THREAD

**Issue by Keridos** [e-valuation/EvaP#2204]
Using docker provider. Start up a fresh docker instance via Vagrant. Try the create superuser command.
It asks for login email and password. Enter credentials. It then crashes due to the postgresql having a constraint that first name of a user must not be null.

**Comment by janno42** [comment]
Will look into that. Please use the "evap" user as described in step 3 of the installation section in the readme for now: https://github.com/e-valuation/EvaP?tab=readme-ov-file#installation-for-development

**Comment by Kakadus** [comment]
I noticed the problem after loading custom data which did not have a superuser.

@richardebeling pointed out that [REQUIRED_FIELDS](https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#django.contrib.auth.models.CustomUser.REQUIRED_FIELDS) should fix it :+1:

**Comment by richardebeling** [comment]
@Keridos do you want to open a pull request that adds the `first_name` and `last_name` fields to the `REQUIRED_FIELDS` class attribute? I would appreciate it! :)

The relevant lines should be
https://github.com/e-valuation/EvaP/blob/a1af82ac3886999e4cecbf4fb88266373270eea8/evap/evaluation/models.py#L1657
and
https://github.com/e-valuation/EvaP/blob/a1af82ac3886999e4cecbf4fb88266373270eea8/evap/evaluation/models.py#L1735

**Comment by Keridos** [comment]
As I got no experience with django projects I have a question there: I can add the fields `first_name_given` and `last_name` to the required fields. But does django know that when calling create_superuser that `first_name` is actually passed from `first_name_given`. The variable names in there are a bit confusing.

**Comment by richardebeling** [comment]
Ah, good point, I think we didn't handle that the way django intends in #1903 (see [the change here](https://github.com/e-valuation/EvaP/pull/1903/files#diff-991236b9d3b760bfaf4f4365df999561c09f03001f36cf2215fee294b13254a8R1602)).

My understanding of the [django docs on custom user profile managers](https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#django.contrib.auth.models.CustomUserManager) is that the argument for `create_user` and `create_superuser` probably should also be renamed from `first_name` to `first_name_given`. Then, I'd expect that having `first_name_given` in the `REQUIRED_FIELDS` works.

(background information regarding the variable naming: Since #1903, we distinguish between `first_name_given`, the first name that the person legally has and may not have control over, and `first_name_chosen`, the preferred first name that the person would like to be addressed by)
